name:               "aipinghua"
description:        "A student in BUAA"

url:                ""
author:             "thinker3197"
email:              "aipinghua@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"

background:         "bg3.jpeg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Bio"
    href:           "#bio"
  - name:           "News"
    href:           "#news"
  - name:           "Education"
    href:           "#education"

posts:
  - title:          "Test Blog"
    url:            ""

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-paginate
